name: protify
description: GUI Friendly for opening games in Linux
publish_to: 'none'
version: 0.1.1+6

environment:
  sdk: '>=3.1.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.3 # Folder Managment
  process_run: ^0.14.1+3 # Command Line
  file_picker: ^8.0.3 # Folder Picker
  flutter_hooks: ^0.20.4 # Mouse Events
  provider: ^6.1.1 # Variables Control
  http: ^1.2.0 # Http requests
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true