name: protify
description: GUI Friendly for opening games in Linux
publish_to: 'none'
version: 0.1.1+6

environment:
  sdk: '>=3.1.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.3.7 # Control the Window
  shared_preferences: ^2.2.2 # Saving Datas
  path: ^1.8.3 # Folder Managment
  process_run: ^0.14.1+3 # Command Line
  filesystem_picker: ^4.1.0 # Folder Picker
  flutter_hooks: ^0.20.4 # Mouse Events
  provider: ^6.1.1 # Variables Control
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true